[package]
name = "felix-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Storage backends and ephemeral cache implementation for the Felix broker"
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords = ["felix", "storage", "cache"]
categories = ["network-programming", "caching"]

[dependencies]
bytes = { workspace = true }
tokio = { workspace = true }
async-trait = "0.1.89"

[dev-dependencies]
tokio = { workspace = true }
