version: "3"

tasks:
  fmt:
    cmds: ["cargo fmt --all"]
  lint:
    cmds: ["cargo clippy --workspace --all-targets --all-features -- -D warnings"]
  test:
    cmds: ["cargo test --workspace"]
  build:
    cmds: ["cargo build --workspace"]
  deny:
    cmds: ["cargo install cargo-deny --version 0.18.3 --locked", "cargo-deny check"]
  demo:
    cmds: ["cargo run -p broker --bin pubsubdemo"]
  demo-pubsub:
    cmds: ["cargo run -p broker --bin pubsubdemo"]
  demo-cache:
    cmds: ["cargo run -p broker --bin cachedemo"]
