version: "3"

tasks:
  fmt:
    cmds: ["cargo fmt --all"]
  lint:
    cmds:
      - "cargo fmt -- --check"
      - "cargo clippy --workspace --all-targets --all-features -- -D warnings"
  clippy:
    cmds: ["cargo clippy --workspace --all-targets --all-features -- -D warnings"]
  test:
    cmds: ["cargo test --workspace"]
  pg:up:
    cmds:
      - >-
        docker inspect felix-pg-tests >/dev/null 2>&1 || docker run -d --rm
        --name felix-pg-tests -e POSTGRES_PASSWORD=postgres -p 55432:5432
        postgres:16-alpine
  pg:down:
    cmds: ["docker rm -f felix-pg-tests >/dev/null 2>&1 || true"]
  coverage:
    env:
      FELIX_TEST_DATABASE_URL: '{{default "postgres://postgres:postgres@host.docker.internal:55432/postgres" .FELIX_TEST_DATABASE_URL}}'
    cmds:
      - "task pg:down"
      - "task pg:up"
      - "cargo llvm-cov --no-cfg-coverage --ignore-filename-regex '(^|.*/)demos/.*' --skip-functions --all-features --workspace"
      - "task pg:down"
  build:
    cmds: ["cargo build --workspace --release"]
  clean:
    cmds:
      - "cargo clean"
      - "rm -rf data/raw/stdout data/raw/latency_demo_runs.jsonl"
  clean-all:
    cmds: ["rm -rf target"]
  deny:
    cmds:
      - "cargo install cargo-deny --version 0.19.0 --locked"
      - "cargo-deny check"
  deny:rsa:default:
    cmds:
      - |
        set +e
        tree=$(cargo tree -i rsa 2>/dev/null)
        status=$?
        set -e
        if [ $status -eq 0 ] && echo "$tree" | rg -q "rsa v"; then
          echo "$tree"
          echo "rsa crate detected in default dependency tree"
          exit 1
        fi
  deny:rsa:oidc:
    cmds:
      - |
        set +e
        tree=$(cargo tree -i rsa -p controlplane --features oidc-rsa 2>/dev/null)
        status=$?
        set -e
        if [ $status -eq 0 ] && echo "$tree" | rg -q "rsa v"; then
          echo "$tree"
          echo "rsa crate detected for oidc-rsa build (expected if RS256 is enabled)"
        else
          echo "rsa crate not detected for oidc-rsa build"
        fi
      - |
        for pkg in broker felix-authz felix-client felix-broker felix-transport felix-wire; do
          set +e
          tree=$(cargo tree -i rsa -p "$pkg" 2>/dev/null)
          status=$?
          set -e
          if [ $status -eq 0 ] && echo "$tree" | rg -q "rsa v"; then
            echo "$tree"
            echo "rsa crate detected in $pkg dependency tree"
            exit 1
          fi
        done
  demo:cache:
    cmds: ["cargo run --release -p broker --bin cache-demo"]
  demo:latency:
    cmds: ["cargo run --release -p broker --bin latency-demo"]
  demo:notifications:
    cmds: ["cargo run --release -p broker --bin pubsub-demo-notifications"]
  demo:orders:
    cmds: ["cargo run --release -p broker --bin pubsub-demo-orders"]
  demo:pubsub:
    cmds: ["cargo run --release -p broker --bin pubsub-demo-simple"]
  demo:rbac-live:
    cmds:
      - "cargo run --manifest-path demos/rbac-live/Cargo.toml"
  demo:cross-tenant-isolation:
    cmds:
      - "task pg:down"
      - "task pg:up"
      - "cargo run --manifest-path demos/cross_tenant_isolation/Cargo.toml"
      - "task pg:down"
  perf:latency-matrix:
    cmds:
      - "python3 scripts/perf/run_latency_matrix.py"
      - "python3 scripts/perf/normalize_and_aggregate.py"
      - "python3 scripts/perf/make_charts.py"
      - "python3 scripts/perf/render_markdown_snippets.py"
  conformance:
    cmds: ["cargo run -p felix-conformance"]
