version: "3"

tasks:
  fmt:
    cmds: ["cargo fmt --all"]
  lint:
    cmds:
      - "cargo fmt -- --check"
      - "cargo clippy --workspace --all-targets --all-features -- -D warnings"
  clippy:
    cmds: ["cargo clippy --workspace --all-targets --all-features -- -D warnings"]
  test:
    cmds: ["cargo test --workspace"]
  pg:up:
    cmds:
      - |
        if docker version >/dev/null 2>&1; then
          docker inspect felix-pg-tests >/dev/null 2>&1 || docker run -d --rm \
            --name felix-pg-tests -e POSTGRES_PASSWORD=postgres -p 55432:5432 \
            postgres:16-alpine
        else
          echo "task: [pg:up] skipping postgres container (docker unavailable)"
        fi
  pg:down:
    cmds: ["docker rm -f felix-pg-tests >/dev/null 2>&1 || true"]
  coverage:
    cmds:
      - "task pg:down"
      - "task pg:up"
      - |
        if [ -n "${FELIX_TEST_DATABASE_URL:-}" ]; then
          FELIX_TEST_DATABASE_URL="$FELIX_TEST_DATABASE_URL" cargo llvm-cov --no-cfg-coverage --skip-functions --all-features --workspace --ignore-filename-regex '(^|/)(demos)(/|$)' --lcov --output-path lcov.info
        elif docker version >/dev/null 2>&1; then
          FELIX_TEST_DATABASE_URL="postgres://postgres:postgres@host.docker.internal:55432/postgres" cargo llvm-cov --no-cfg-coverage --skip-functions --all-features --workspace --ignore-filename-regex '(^|/)(demos)(/|$)' --lcov --output-path lcov.info
        else
          cargo llvm-cov --no-cfg-coverage --skip-functions --all-features --workspace --ignore-filename-regex '(^|/)(demos)(/|$)' --lcov --output-path lcov.info
        fi
      - "cargo llvm-cov report --summary-only"
      - "task pg:down"
  coverage:demos:
    cmds:
      - "task pg:down"
      - "task pg:up"
      - |
        if [ -n "${FELIX_TEST_DATABASE_URL:-}" ]; then
          FELIX_TEST_DATABASE_URL="$FELIX_TEST_DATABASE_URL" cargo llvm-cov --no-cfg-coverage --skip-functions --all-features --workspace --ignore-filename-regex '^(?!.*?/demos/)' --lcov --output-path lcov-demos.info
        elif docker version >/dev/null 2>&1; then
          FELIX_TEST_DATABASE_URL="postgres://postgres:postgres@host.docker.internal:55432/postgres" cargo llvm-cov --no-cfg-coverage --skip-functions --all-features --workspace --ignore-filename-regex '^(?!.*?/demos/)' --lcov --output-path lcov-demos.info
        else
          cargo llvm-cov --no-cfg-coverage --skip-functions --all-features --workspace --ignore-filename-regex '^(?!.*?/demos/)' --lcov --output-path lcov-demos.info
        fi
      - "cargo llvm-cov report --summary-only"
      - "task pg:down"
  build:
    cmds: ["cargo build --workspace --release"]
  clean:
    cmds:
      - "cargo clean"
      - "rm -rf data/raw/stdout data/raw/latency_demo_runs.jsonl"
  clean-all:
    cmds: ["rm -rf target"]
  deny:
    cmds:
      - "cargo install cargo-deny --version 0.19.0 --locked"
      - "cargo-deny check"
  deny:rsa:default:
    cmds:
      - |
        for pkg in broker felix-authz felix-client felix-broker felix-transport felix-wire; do
          set +e
          tree=$(cargo tree -i rsa -p "$pkg" 2>/dev/null)
          status=$?
          set -e
          if [ $status -eq 0 ] && echo "$tree" | rg -q "rsa v"; then
            echo "$tree"
            echo "rsa crate detected in $pkg dependency tree"
            exit 1
          fi
        done
  demo:cache:
    cmds: ["cargo run --release -p broker --bin cache-demo"]
  demo:latency:
    cmds: ["cargo run --release -p broker --bin latency-demo --all-features"]
  demo:notifications:
    cmds: ["cargo run --release -p broker --bin pubsub-demo-notifications"]
  demo:orders:
    cmds: ["cargo run --release -p broker --bin pubsub-demo-orders"]
  demo:pubsub:
    cmds: ["cargo run --release -p broker --bin pubsub-demo-simple"]
  demo:rbac-live:
    cmds:
      - "cargo run --manifest-path demos/rbac-live/Cargo.toml"
  demo:cross-tenant-isolation:
    cmds:
      - "task pg:down"
      - "task pg:up"
      - "cargo run --manifest-path demos/cross_tenant_isolation/Cargo.toml"
      - "task pg:down"
  perf:latency-matrix:
    cmds:
      - "python3 scripts/perf/run_latency_matrix.py"
      - "python3 scripts/perf/normalize_and_aggregate.py"
      - "python3 scripts/perf/make_charts.py"
      - "python3 scripts/perf/render_markdown_snippets.py"
  conformance:
    cmds: ["cargo run -p felix-conformance"]
