version: "3"

tasks:
  fmt:
    cmds: ["cargo fmt --all"]
  lint:
    cmds:
      - "cargo fmt -- --check"
      - "cargo clippy --workspace --all-targets --all-features -- -D warnings"
  clippy:
    cmds: ["cargo clippy --workspace --all-targets --all-features -- -D warnings"]
  test:
    cmds: ["cargo test --workspace"]
  coverage:
    cmds: ["cargo llvm-cov --ignore-filename-regex 'services/broker/src/bin/.*demo.*' --skip-functions --all-features --workspace"]
  build:
    cmds: ["cargo build --workspace"]
  clean:
    cmds:
      - "cargo clean"
      - "rm -rf data/raw/stdout data/raw/latencydemo_runs.jsonl"
  clean-all:
    cmds: ["rm -rf target"]
  deny:
    cmds: ["cargo install cargo-deny --version 0.19.0 --locked", "cargo-deny check"]
  demo:
    cmds: ["cargo run -p broker --bin pubsubdemo"]
  demo-pubsub:
    cmds: ["cargo run -p broker --bin pubsubdemo"]
  demo-cache:
    cmds: ["cargo run -p broker --bin cachedemo"]
  demo-latency:
    cmds: ["cargo run -p broker --bin latencydemo"]
  perf:latency-matrix:
    cmds:
      - "python3 scripts/perf/run_latency_matrix.py"
      - "python3 scripts/perf/normalize_and_aggregate.py"
      - "python3 scripts/perf/make_charts.py"
      - "python3 scripts/perf/render_markdown_snippets.py"
  conformance:
    cmds: ["cargo run -p felix-conformance"]
