version: "3"

tasks:
  fmt:
    cmds: ["cargo fmt --all"]
  lint:
    cmds:
      - "cargo fmt -- --check"
      - "cargo clippy --workspace --all-targets --all-features -- -D warnings"
  clippy:
    cmds: ["cargo clippy --workspace --all-targets --all-features -- -D warnings"]
  test:
    cmds: ["cargo test --workspace"]
  pg:up:
    cmds:
      - >-
        docker inspect felix-pg-tests >/dev/null 2>&1 || docker run -d --rm
        --name felix-pg-tests -e POSTGRES_PASSWORD=postgres -p 55432:5432
        postgres:16-alpine
  pg:down:
    cmds: ["docker rm -f felix-pg-tests >/dev/null 2>&1 || true"]
  coverage:
    env:
      FELIX_TEST_DATABASE_URL: '{{default "postgres://postgres:postgres@host.docker.internal:55432/postgres" .FELIX_TEST_DATABASE_URL}}'
    cmds:
      - "task pg:up"
      - "cargo llvm-cov --no-cfg-coverage --ignore-filename-regex 'services/broker/src/bin/.*demo.*|services/broker/src/auth_demo.rs' --skip-functions --all-features --workspace"
      - "task pg:down"
  build:
    cmds: ["cargo build --workspace --release"]
  clean:
    cmds:
      - "cargo clean"
      - "rm -rf data/raw/stdout data/raw/latencydemo_runs.jsonl"
  clean-all:
    cmds: ["rm -rf target"]
  deny:
    cmds:
      - "cargo install cargo-deny --version 0.19.0 --locked"
      - "cargo-deny check"
      - "if cargo tree -i rsa | rg -q \"rsa v\"; then echo \"rsa crate detected in dependency tree\"; exit 1; fi"
  demo:
    cmds: ["cargo run --release -p broker --bin pubsubdemo"]
  demo-pubsub:
    cmds: ["cargo run --release -p broker --bin pubsubdemo"]
  demo-cache:
    cmds: ["cargo run --release -p broker --bin cachedemo"]
  demo-latency:
    cmds: ["cargo run --release -p broker --bin latencydemo"]
  perf:latency-matrix:
    cmds:
      - "python3 scripts/perf/run_latency_matrix.py"
      - "python3 scripts/perf/normalize_and_aggregate.py"
      - "python3 scripts/perf/make_charts.py"
      - "python3 scripts/perf/render_markdown_snippets.py"
  conformance:
    cmds: ["cargo run -p felix-conformance"]
