#!/usr/bin/env bash
# Turn on TLS for the Redpanda kafka API on every broker, and drop the CA on the
# clients' truststore path. This is a fairness requirement, not a nicety: Felix
# runs QUIC/TLS unconditionally (that crypto is the measured broker-CPU cost), so
# comparing against a plaintext Kafka listener would hand Redpanda kernel sendfile
# zero-copy that Felix structurally cannot use. TLS on both sides or the number
# is meaningless.
#
# One self-signed CA + one server cert whose SANs cover all three broker IPs
# (generated by the caller into $CERTDIR). Server-auth only (require_client_auth
# false), mirroring Felix's server-authenticated TLS.
set -euo pipefail
: "${SESSION:?SESSION=<name>}"
: "${CERTDIR:?CERTDIR=<dir with ca.crt node.crt node.key>}"
here="$(cd "$(dirname "$0")" && pwd)"
source "${here}/compare-lib.sh"
source "${here}/sessions/${SESSION}.env"
export GROUP

IFS=',' read -ra BIPS <<<"${BROKER_IPS}"
IFS=',' read -ra CIPS <<<"${CLIENT_IPS}"
CA_B64="$(base64 < "${CERTDIR}/ca.crt" | tr -d '\n')"
CRT_B64="$(base64 < "${CERTDIR}/node.crt" | tr -d '\n')"
KEY_B64="$(base64 < "${CERTDIR}/node.key" | tr -d '\n')"

for i in "${!BIPS[@]}"; do
  self="${BIPS[$i]}"
  echo ">> enabling TLS on broker-${i} (${self})"
  run_on_str "$(broker_vm "${i}")" "$(cat <<REMOTE
#!/bin/sh
set -e
mkdir -p /etc/redpanda/certs
echo '${CA_B64}'  | base64 -d > /etc/redpanda/certs/ca.crt
echo '${CRT_B64}' | base64 -d > /etc/redpanda/certs/node.crt
echo '${KEY_B64}' | base64 -d > /etc/redpanda/certs/node.key
chown -R redpanda:redpanda /etc/redpanda/certs
chmod 640 /etc/redpanda/certs/node.key
# Name the single kafka listener so a TLS entry can bind to it, then attach TLS.
rpk redpanda config set redpanda.kafka_api '[{"name":"external","address":"${self}","port":9092}]'
rpk redpanda config set redpanda.advertised_kafka_api '[{"name":"external","address":"${self}","port":9092}]'
rpk redpanda config set redpanda.kafka_api_tls '[{"name":"external","enabled":true,"cert_file":"/etc/redpanda/certs/node.crt","key_file":"/etc/redpanda/certs/node.key","require_client_auth":false}]'
echo __RUNOK__
REMOTE
)" | tail -1
done

# Rolling restart so the cluster keeps quorum through the change.
for i in "${!BIPS[@]}"; do
  echo ">> restarting broker-${i}"
  run_on_str "$(broker_vm "${i}")" "$(cat <<'REMOTE'
#!/bin/sh
systemctl restart redpanda
sleep 8
systemctl is-active redpanda
echo __RUNOK__
REMOTE
)" | tail -1
  sleep 5
done

# CA onto both clients (kafka clients verify the server cert against this).
for i in "${!CIPS[@]}"; do
  echo ">> CA -> client-${i}"
  run_on_str "$(client_vm "${i}")" "$(cat <<REMOTE
#!/bin/sh
mkdir -p /opt/certs
echo '${CA_B64}' | base64 -d > /opt/certs/ca.crt
echo __RUNOK__
REMOTE
)" | tail -1
done

echo ">> verifying TLS kafka API"
run_on_str "$(client_vm 0)" "$(cat <<REMOTE
#!/bin/sh
/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server ${BIPS[0]}:9092 \
  --command-config /dev/stdin <<CFG 2>&1 | head -3
security.protocol=SSL
ssl.truststore.type=PEM
ssl.truststore.location=/opt/certs/ca.crt
CFG
echo __RUNOK__
REMOTE
)" | sed -n '/stdout/,/__RUNOK__/p'
echo ">> TLS on. Re-bench with TLS=1."
