//! The OpenAPI document. Every public route and schema must be registered
//! here by hand — an endpoint left out is invisible to docs and generated
//! clients, and nothing else in the build notices.
use utoipa::OpenApi;

use crate::api::{
    caches, namespaces, nodes, regions, shard_assignments, shard_moves, streams, system, tenants,
    types::{
        CacheChangesResponse, CacheCreateRequest, CacheListResponse, CacheSnapshotResponse,
        ErrorResponse, FeatureFlags, HealthStatus, ListRegionsResponse, NamespaceChangesResponse,
        NamespaceCreateRequest, NamespaceListResponse, NamespaceSnapshotResponse,
        NodeHeartbeatRequest, NodeHeartbeatResponse, NodeListResponse, NodePlacement,
        NodeRegistrationRequest, NodeRegistrationResponse, NodeView, PlacementPlanResponse,
        PlacementStatusResponse, PlannedShard, Region, ShardAssignmentChangesResponse,
        ShardAssignmentListResponse, ShardAssignmentSnapshotResponse, ShardMove,
        ShardMoveListResponse, ShardMoveRequest, ShardMoveResponse, ShardMoveStep,
        StreamChangesResponse, StreamCreateRequest, StreamListResponse, StreamSnapshotResponse,
        SystemInfo, TenantChangesResponse, TenantCreateRequest, TenantListResponse,
        TenantSnapshotResponse,
    },
};
use crate::auth::admin;
use crate::auth::admin::{GroupingRequest, PolicyRequest};
use crate::auth::exchange::{self, TokenExchangeRequest, TokenExchangeResponse};
use crate::auth::idp_registry::IdpIssuerConfig;
use crate::auth::jwks::{self, JwksResponse};
use crate::auth::rbac::policy_store::{GroupingRule, PolicyRule};
use crate::model::{
    Cache, CacheChange, CacheChangeOp, CacheKey, CachePatchRequest, ConsistencyLevel,
    DeliveryGuarantee, MoveReason, Namespace, NamespaceChange, NamespaceChangeOp, NamespaceKey,
    Node, NodeCapacity, NodeChange, NodeChangeOp, NodeLifecycle, NodePatchRequest, NodeSpec,
    NodeStatus, RetentionPolicy, ShardAssignment, ShardAssignmentChange, ShardAssignmentChangeOp,
    ShardKey, ShardKind, ShardState, Stream, StreamChange, StreamChangeOp, StreamKey, StreamKind,
    StreamPatchRequest, Tenant, TenantChange, TenantChangeOp,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "felix-controlplane",
        version = "v1",
        description = "Felix control plane HTTP API"
    ),
    paths(
        system::system_info,
        system::system_health,
        regions::list_regions,
        regions::get_region,
        exchange::exchange_token,
        jwks::tenant_jwks,
        admin::upsert_idp_issuer,
        admin::delete_idp_issuer,
        admin::add_policy,
        admin::add_grouping,
        tenants::list_tenants,
        tenants::create_tenant,
        tenants::delete_tenant,
        tenants::tenant_snapshot,
        tenants::tenant_changes,
        namespaces::list_namespaces,
        namespaces::create_namespace,
        namespaces::delete_namespace,
        namespaces::namespace_snapshot,
        namespaces::namespace_changes,
        caches::cache_snapshot,
        caches::cache_changes,
        streams::stream_snapshot,
        streams::stream_changes,
        streams::list_streams,
        caches::list_caches,
        streams::create_stream,
        streams::get_stream,
        streams::patch_stream,
        streams::delete_stream,
        caches::create_cache,
        caches::get_cache,
        caches::patch_cache,
        caches::delete_cache,
        nodes::reports::report_health,
        nodes::register_node,
        nodes::drain_node,
        nodes::deregister_node,
        nodes::listing::list_nodes,
        nodes::listing::get_node,
        nodes::patch_node,
        nodes::delete_node,
        shard_assignments::list_shard_assignments,
        shard_assignments::shard_assignment_snapshot,
        shard_assignments::shard_assignment_changes,
        shard_moves::list_shard_moves,
        shard_moves::start_shard_move,
        shard_moves::cancel_shard_move,
        shard_moves::placement_plan,
        shard_moves::pause_placement,
        shard_moves::resume_placement
    ),
    components(schemas(
        FeatureFlags,
        SystemInfo,
        HealthStatus,
        Region,
        ListRegionsResponse,
        ErrorResponse,
        Tenant,
        TenantCreateRequest,
        TenantListResponse,
        TenantSnapshotResponse,
        TenantChange,
        TenantChangesResponse,
        TenantChangeOp,
        Namespace,
        NamespaceKey,
        NamespaceCreateRequest,
        NamespaceListResponse,
        NamespaceSnapshotResponse,
        NamespaceChange,
        NamespaceChangesResponse,
        NamespaceChangeOp,
        Cache,
        CacheKey,
        CacheCreateRequest,
        CachePatchRequest,
        CacheListResponse,
        CacheSnapshotResponse,
        CacheChange,
        CacheChangesResponse,
        CacheChangeOp,
        Stream,
        StreamKind,
        StreamCreateRequest,
        StreamListResponse,
        StreamSnapshotResponse,
        StreamChange,
        StreamChangesResponse,
        StreamChangeOp,
        StreamKey,
        StreamPatchRequest,
        RetentionPolicy,
        ConsistencyLevel,
        DeliveryGuarantee,
        Node,
        NodeSpec,
        NodeStatus,
        NodeCapacity,
        NodeLifecycle,
        NodePatchRequest,
        NodeChange,
        NodeChangeOp,
        NodeHeartbeatRequest,
        NodeHeartbeatResponse,
        NodeRegistrationRequest,
        NodeRegistrationResponse,
        NodeView,
        NodePlacement,
        NodeListResponse,
        ShardAssignment,
        ShardKey,
        ShardState,
        ShardAssignmentListResponse,
        ShardAssignmentSnapshotResponse,
        ShardAssignmentChangesResponse,
        ShardAssignmentChange,
        ShardAssignmentChangeOp,
        ShardKind,
        MoveReason,
        ShardMove,
        ShardMoveStep,
        ShardMoveListResponse,
        ShardMoveRequest,
        ShardMoveResponse,
        PlannedShard,
        PlacementPlanResponse,
        PlacementStatusResponse,
        TokenExchangeRequest,
        TokenExchangeResponse,
        IdpIssuerConfig,
        PolicyRequest,
        GroupingRequest,
        PolicyRule,
        GroupingRule,
        JwksResponse
    )),
    tags(
        (name = "system", description = "System and discovery endpoints"),
        (name = "regions", description = "Region metadata"),
        (name = "auth", description = "Authentication and token exchange"),
        (name = "tenants", description = "Tenant management"),
        (name = "namespaces", description = "Namespace management"),
        (name = "streams", description = "Stream management"),
        (name = "caches", description = "Cache management"),
        (name = "nodes", description = "Broker membership"),
        (name = "placement", description = "Shard moves and placement, for operators")
    )
)]
pub struct ApiDoc;

#[cfg(test)]
mod tests;
