[package]
name = "felix-broker"
version.workspace = true
edition.workspace = true
license = "Elastic-2.0"
rust-version.workspace = true

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
metrics = "0.24"
felix-storage = { path = "../felix-storage", version = "0.1.1" }
felix-wire = { path = "../felix-wire", version = "0.1.1" }
arc-swap = "1.8"
ahash = "0.8"
hashbrown = { version = "0.16", features = ["equivalent"] }
slab = "0.4"
parking_lot = "0.12"

[features]
default = []
telemetry = []
perf_debug = []

[dev-dependencies]
serial_test = "3"
